### PR TITLE
do not request exclusive consumer access

### PR DESCRIPTION
**Pull request by velimir**

### CODE REVIEW

**Comment by jandelgado** [comment]
What problem does the MR solve, could you please explain?

**Comment by velimir** [comment]
If a queue has any consumers, then rabbitmq won’t allow rabtab to subscribe to it, as it tries to subscribe exclusively.
Sometimes it’s useful to subscribe to the queue and drain messages from the queue when queue  have other consumers.

**Comment by jandelgado** [comment]
The use of the `exclusive` mode originated in the "tap" command, where it makes sense, that no other consumers subscribe to the (temporary) queue bound to the (temporary) tap-exchange.

I assume your use-case is the "sub" command, where you subscribe to an existing queue, correct? 
In general I would prefer making the setting configurable through the cli, like e.g.:

`rabtap sub QUEUE [--uri URI] [--saveto=DIR] [-jkvnx]`, e.g. where `-x`  would enable exclusive mode. Example usage: `rabtap sub testqueue -x`

**Comment by velimir** [comment]
> I assume your use-case is the "sub" command, where you subscribe to an existing queue, correct?

Yes.

> I would prefer making the setting configurable through the cli

I'll see if I can send a PR near time soon.

**Comment by jandelgado** [comment]
Excellent - don't forget the unit tests

**Comment by jandelgado** [comment]
I've added the feature in the v1.14 release
* SUBscribe mode will use non-exclusive mode
* TAP will use exclusive mode (like before)

**Pull request closed without merging**
